% % plots
%% Retrieved profile vs height
% TitleFigure='Retrieved_ext_profile_z';
% figure('name', TitleFigure, 'NumberTitle','off', ...
%     'units','centimeters','Position',[2 50 18 25]);
% tt=214;
%  plot(extp(tt,:),z,'-r', ...
%      alpha_ret_ss_nc(tt,:),z,'.-k', ...
%      alpha_ret_ss(tt,:),z, '--k', ...
%      alpha_ret_ms_nc(tt,:),z,'.-b', ...
%      alpha_ret_ms(tt,:),z,'--b', ...
%      alpha_ret_ms2ss(tt,:),z,'-.m', 'LineWidth', 1.25)
%  line('XData', [0 0.05], 'YData', [z(io(tt)) z(io(tt))], ...
%     'LineWidth', 1.0, 'LineStyle', '-.', 'Color', 'g')
%  xlim([0 0.05])
%  ylim([0 500])
%  l = legend('True extinction', ...
%     'Retrieved extinction from Ba_{SS}', ...
%     'Retrieved extinction from Ba_{SS} with RES correction', ...
%     'Retrieved extinction from Ba_{MS}', ...
%     'Retrieved extinction from Ba_{MS} with RES correction', ...
%     'Retrieved extinction from Ba_{MS} with SS & RES correction ', ...
%     'Normalisation height');

%% Retrieved profile vs tau
for i=41:50
TitleFigure='Retrieved_ext_profile_tau';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'units','centimeters','Position',[2 50 18 18]);
tt=i;
zz = io_uv(tt);
 plot(ext_ray_uv(tt,1:zz),tau_uv(tt,1:zz),'-r', ...
     alpha_ret_ss_nc_uv(tt,1:zz),tau_uv(tt,1:zz),'.-k', ...
     alpha_ret_ss_uv(tt,1:zz),tau_uv(tt,1:zz), '--k', ...
     alpha_ret_ms_nc_uv(tt,1:zz),tau_uv(tt,1:zz),'.-b', ...
     alpha_ret_ms_uv(tt,1:zz),tau_uv(tt,1:zz),'--b', ...
     alpha_ret_ms2ss_uv(tt,1:zz),tau_uv(tt,1:zz),'-.m', 'LineWidth', 1.25)
 line('XData', [0 0.05], 'YData', ...
     [tau_uv(tt,io_uv(tt)) tau_uv(tt,io_uv(tt))], ...
    'LineWidth', 1.0, 'LineStyle', '-.', 'Color', 'g')
 xlim([0 0.05])
 ylim([0 3.5])
 t = title('Retreived Extinction Coefficient');
 set(t, 'horizontalAlignment', 'left')
 set(t, 'units', 'normalized')
 h1 = get(t, 'position');
 set(t, 'position', [0 h1(2) h1(3)])
 l = legend({'True extinction', ...
    'Retrieved extinction from Ba_{SS}', ...
    'Retrieved extinction from Ba_{SS} with RES correction', ...
    'Retrieved extinction from Ba_{MS}', ...
    'Retrieved extinction from Ba_{MS} with RES correction', ...
    'Retrieved extinction from Ba_{MS} with SS & RES correction ', ...
    'Normalisation height'}, ...
    'Location','SouthOutside', 'Orientation', 'Vertical', ...
    'FontSize', 12);
xlabel('\alpha [m^{-1} sr]')
ylabel('\tau ')
set(gca,'FontSize',14)
saveas(gcf,sprintf(TitleFigure),'epsc')
export_fig(sprintf(TitleFigure), '-eps', '-transparent')
end
%% Plot alpha slope
t1 = 1; 
norm_up = norm_down_uv + nh_uv;
TitleFigure='Slope_method';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'Units','centimeters','Position',[10 30 18 18]);
p1 = plot( ...  
    ext_ray_uv(t1,:), z_uv,'.-r',...
    alpha_ss_slope_corr_uv(t1,:), z_uv, '.-k', ...
    'LineWidth',1.5,...
    'MarkerSize',10);
ylim([0 500])
t = title('Slope Method Extinction Retrieval');
set(t, 'horizontalAlignment', 'left')
set(t, 'units', 'normalized')
h1 = get(t, 'position');
set(t, 'position', [0 h1(2) h1(3)])
grid on
hold on
% xlim([-0.10-mean(Ext_uv(t1,1:end-1)) 0.06])
% ylim([0 z(norm_up(t1) +5)])
line('XData', [0 max(Ext_uv(t1,1:end-1))], 'YData', ...
    [z_uv(io_uv(t1)) z_uv(io_uv(t1))], 'LineWidth', 1.5, ...
     'Color', 'b')
line('XData', [0 max(Ext_uv(t1,1:end-1))], 'YData', ...
    [z_uv(id_cb_lidar_uv(t1)) z_uv(id_cb_lidar_uv(t1))], 'LineWidth', 1.5, ...
     'Color', 'g')
legend('"True" extinction', 'Slope method retrieval', ...
    'Normalisation height', 'Cloud base height', 'Location', ...
    'northwest')
xlabel('\alpha [m^{-1} sr]')
ylabel('Height [m] ')
set(gca,'FontSize',14)
saveas(gcf,sprintf(TitleFigure),'epsc')
export_fig(sprintf(TitleFigure), '-eps', '-transparent')
%%
t1=151;
TitleFigure='Signal';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'Units','centimeters','Position',[10 30 18 18]);
p1 = plot( ...  
    Ba_MS_uv(t1,1:end-1), z_uv(1:end-1),'.-r',...
    'LineWidth',1.5,...
    'MarkerSize',10);
% ylim([0 10])
t = title('Attenuated Backscatter Coefficient Profile');
set(t, 'horizontalAlignment', 'left')
set(t, 'units', 'normalized')
h1 = get(t, 'position');
set(t, 'position', [0 h1(2) h1(3)])
grid on
hold on
% xlim([0 max(beta_atten_SS(t1,1:end-1))+mean(beta_atten_SS(t1,1:end-1))])
%ylim([0 z(norm_up(t1) +6)])
line('XData', [0 max(Ba_MS_uv(t1,1:end-1))], 'YData', ...
    [z_uv(norm_up_uv(t1)) z_uv(norm_up_uv(t1))], ...
    'LineWidth', 1.5, ...
     'Color', 'b')
line('XData', [0 max(Ba_MS_uv(t1,1:end-1))], 'YData', ...
    [z_uv(norm_down_uv(t1)) z_uv(norm_down_uv(t1))], 'LineWidth', 1.5, ...
    'Color', 'b')
legend('ATB', 'Normalisation interval boundaries', ...
    'Location','northwest')
xlabel('ATB [m^{-1} sr^{-1}]')
ylabel('Height [m] ')
set(gca,'FontSize',14)
saveas(gcf,sprintf(TitleFigure),'epsc')
export_fig(sprintf(TitleFigure), '-eps', '-transparent')

% t1=151;
% norm_up2 = norm_down + nh;
% TitleFigure='Signal';
% figure('name', TitleFigure, 'NumberTitle','off', ...
%     'Units','centimeters','Position',[10 30 15 15]);
% p1 = plot( ...  
%     Ba_MS(t1,1:end-1), z(1:end-1),'.-r',...
%     'LineWidth',1.5,...
%     'MarkerSize',10);
% % ylim([0 10])
% t = title('Attenuated Backscatter Coefficient Profile (res 2.5 m)');
% set(t, 'horizontalAlignment', 'left')
% set(t, 'units', 'normalized')
% h1 = get(t, 'position');
% set(t, 'position', [0 h1(2) h1(3)])
% grid on
% hold on
% % xlim([0 max(beta_atten_SS(t1,1:end-1))+mean(beta_atten_SS(t1,1:end-1))])
% %ylim([0 z(norm_up(t1) +6)])
% line('XData', [0 max(Ba_MS(t1,1:end-1))], 'YData', ...
%     [z(norm_up2(t1)) z(norm_up2(t1))], ...
%     'LineWidth', 1.5, ...
%      'Color', 'b')
% line('XData', [0 max(Ba_MS(t1,1:end-1))], 'YData', ...
%     [z(norm_down(t1)) z(norm_down(t1))], 'LineWidth', 1.5, ...
%     'Color', 'b')
% legend('ATB', 'Normalisation interval boundaries')
% xlabel('ATB [m^{-1} sr^{-1}]')
% ylabel('Height [m] ')
% set(gca,'FontSize',14)