% % plots
%% Retrieved profile vs height
% TitleFigure='Retrieved_ext_profile_z';
% figure('name', TitleFigure, 'NumberTitle','off', ...
%     'units','centimeters','Position',[2 50 18 25]);
% tt=214;
%  plot(extp(tt,:),z,'-r', ...
%      alpha_ret_ss_nc(tt,:),z,'.-k', ...
%      alpha_ret_ss(tt,:),z, '--k', ...
%      alpha_ret_ms_nc(tt,:),z,'.-b', ...
%      alpha_ret_ms(tt,:),z,'--b', ...
%      alpha_ret_ms2ss(tt,:),z,'-.m', 'LineWidth', 1.25)
%  line('XData', [0 0.05], 'YData', [z(io(tt)) z(io(tt))], ...
%     'LineWidth', 1.0, 'LineStyle', '-.', 'Color', 'g')
%  xlim([0 0.05])
%  ylim([0 500])
%  l = legend('True extinction', ...
%     'Retrieved extinction from Ba_{SS}', ...
%     'Retrieved extinction from Ba_{SS} with RES correction', ...
%     'Retrieved extinction from Ba_{MS}', ...
%     'Retrieved extinction from Ba_{MS} with RES correction', ...
%     'Retrieved extinction from Ba_{MS} with SS & RES correction ', ...
%     'Normalisation height');

%% Retrieved profile vs tau
TitleFigure='Retrieved_ext_profile_tau';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'units','centimeters','Position',[2 50 15 20]);
tt=214;
zz = io(tt)+1;
 plot(extp(tt,1:zz),tau(tt,1:zz),'-r', ...
     alpha_ret_ss_nc(tt,1:zz),tau(tt,1:zz),'.-k', ...
     alpha_ret_ss(tt,1:zz),tau(tt,1:zz), '--k', ...
     alpha_ret_ms_nc(tt,1:zz),tau(tt,1:zz),'.-b', ...
     alpha_ret_ms(tt,1:zz),tau(tt,1:zz),'--b', ...
     alpha_ret_ms2ss(tt,1:zz),tau(tt,1:zz),'-.m', 'LineWidth', 1.25)
 line('XData', [0 0.05], 'YData', [tau(tt,io(tt)) tau(tt,io(tt))], ...
    'LineWidth', 1.0, 'LineStyle', '-.', 'Color', 'g')
 xlim([0 0.05])
 ylim([0 1.5])
 t = title('Retreived Extinction Coefficient');
 set(t, 'horizontalAlignment', 'left')
 set(t, 'units', 'normalized')
 h1 = get(t, 'position');
 set(t, 'position', [0 h1(2) h1(3)])
 l = legend('True extinction', ...
    'Retrieved extinction from Ba_{SS}', ...
    'Retrieved extinction from Ba_{SS} with RES correction', ...
    'Retrieved extinction from Ba_{MS}', ...
    'Retrieved extinction from Ba_{MS} with RES correction', ...
    'Retrieved extinction from Ba_{MS} with SS & RES correction ', ...
    'Normalisation height','Location','southoutside','Orientation','vertical',...
    'Fontsize', 12);
xlabel('\alpha [m^{-1} sr]')
ylabel('\tau ')
set(gca,'FontSize',14)
% saveas(gcf,sprintf(TitleFigure),'epsc')
export_fig(sprintf(TitleFigure), '-eps', '-transparent')

%% Plot alpha slope
t1 = 18;
TitleFigure='Slope_method';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'Units','centimeters','Position',[10 30 15 15]);
p1 = plot( ...  
    extp(t1,:), z,'.-r',...
    alpha_ss_slope_corr(t1,:), z, '.-k', ...
    'LineWidth',1.5,...
    'MarkerSize',10);
ylim([0 10])
t = title('Slope Method Extinction Retrieval');
set(t, 'horizontalAlignment', 'left')
set(t, 'units', 'normalized')
h1 = get(t, 'position');
set(t, 'position', [0 h1(2) h1(3)])
grid on
hold on
xlim([-0.10-mean(Ext(t1,1:end-1)) 0.06])
ylim([0 z(norm_up(t1) +5)])
line('XData', [0 max(Ext(t1,1:end-1))], 'YData', [z(io(t1)) z(io(t1))], 'LineWidth', 1.5, ...
     'Color', 'b')
line('XData', [0 max(Ext(t1,1:end-1))], 'YData', [z(id_cb_lidar(t1)) z(id_cb_lidar(t1))], 'LineWidth', 1.5, ...
     'Color', 'g')
legend('"True" extinction', 'Slope method retrieval', 'Normalisation height', 'Cloud base height')
xlabel('\alpha [m^{-1} sr]')
ylabel('Height [m] ')
set(gca,'FontSize',14)
% saveas(gcf,sprintf(TitleFigure),'epsc')
export_fig(sprintf(TitleFigure), '-eps', '-transparent')
%%
t1=205;
TitleFigure='Signal';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'Units','centimeters','Position',[10 30 15 15]);
p1 = plot( ...  
    Ba_MS(t1,1:end-1), z(1:end-1),'.-r',...
    'LineWidth',1.5,...
    'MarkerSize',10);
% ylim([0 10])
t = title('Attenuated Backscatter Coefficient Profile');
set(t, 'horizontalAlignment', 'left')
set(t, 'units', 'normalized')
h1 = get(t, 'position');
set(t, 'position', [0 h1(2) h1(3)])
grid on
hold on
% xlim([0 max(beta_atten_SS(t1,1:end-1))+mean(beta_atten_SS(t1,1:end-1))])
ylim([0 z(norm_up(t1) +6)])
line('XData', [0 max(Ba_MS(t1,1:end-1))], 'YData', [z(norm_up(t1)) z(norm_up(t1))], 'LineWidth', 1.5, ...
     'Color', 'b')
line('XData', [0 max(Ba_MS(t1,1:end-1))], 'YData', [z(norm_down(t1)) z(norm_down(t1))], 'LineWidth', 1.5, ...
    'Color', 'b')
legend('ATB', 'Normalisation interval boundaries')
xlabel('ATB [m^{-1} sr^{-1}]')
ylabel('Height [m] ')
set(gca,'FontSize',14)
% saveas(gcf,sprintf(TitleFigure),'epsc')
export_fig(sprintf(TitleFigure), '-eps', '-transparent')