%% Plot
TitleFigure='Retrieved_ext_profile';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'units','centimeters','Position',[2 50 18 25]);
tt=151;
 plot(Ext_uv(tt,:),z_uv,'-.r', ...
     alpha_ret_ss_nc_uv(tt,:),z_uv,'--k', ...
     alpha_ret_ss_uv(tt,:),z_uv, '.-k', ...
     alpha_ret_ms_nc_uv(tt,:),z_uv,'--b', ...
     alpha_ret_ms_uv(tt,:),z_uv,'.-b', ...
     alpha_ret_ms2ss_nc_uv(tt,:),z_uv, '-g', ...
     alpha_ret_ms2ss_uv(tt,:),z_uv,'.-m', 'LineWidth', 1.25)
 line('XData', [0 0.05], 'YData', [z_uv(io_uv(tt)) z_uv(io_uv(tt))], ...
    'LineWidth', 1.0, 'LineStyle', '-.', 'Color', 'c')
 xlim([0 0.05])
 ylim([0 500])
 l = legend('True extinction', ...
    'Retrieved extinction from Ba_{SS}', ...
    'Retrieved extinction from Ba_{SS} with RES correction', ...
    'Retrieved extinction from Ba_{MS}', ...
    'Retrieved extinction from Ba_{MS} with RES correction', ...
    'Retrieved extinction from Ba_{MS} with SS correction', ...
    'Retrieved extinction from Ba_{MS} with SS & RES correction ', ...
    'Normalisation height');

TitleFigure='Retrieved_ext_profile uv Lidar resolution';
figure('name', TitleFigure, 'NumberTitle','off', ...
    'units','centimeters','Position',[2 50 18 25]);
tt=150;
 plot(Ext(tt,:),z,'-.r', ...
     alpha_ret_ss_nc_uv(tt,:),z_uv,'--k', ...
     alpha_ret_ss_uv(tt,:),z_uv, '.-k', ...
     alpha_ret_ms_nc_uv(tt,:),z_uv,'--b', ...
     alpha_ret_ms_uv(tt,:),z_uv,'.-b', ...
     alpha_ret_ms2ss_nc_uv(tt,:),z_uv, '-g', ...
     alpha_ret_ms2ss_uv(tt,:),z_uv,'.-m', 'LineWidth', 1.25)
 line('XData', [0 0.05], 'YData', [z(io(tt)) z(io(tt))], ...
    'LineWidth', 1.0, 'LineStyle', '-.', 'Color', 'c')
 xlim([0 0.05])
 ylim([0 500])
 l = legend('True extinction', ...
    'Retrieved extinction from Ba_{SS}', ...
    'Retrieved extinction from Ba_{SS} with RES correction', ...
    'Retrieved extinction from Ba_{MS}', ...
    'Retrieved extinction from Ba_{MS} with RES correction', ...
    'Retrieved extinction from Ba_{MS} with SS correction', ...
    'Retrieved extinction from Ba_{MS} with SS & RES correction ', ...
    'Normalisation height');

